resolver: lts-7.14

packages:
  - '.'
  - location:
      git: git@github.com:haskell-distributed/distributed-process.git
      commit: f1ad0741ab19435a1de435ccb7126268ba85bf14
extra-deps: []

flags: {}

extra-package-dbs: []
